export const constants = {
  CHARSET: "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_",
  CODE_LENGTH: 6,

  // BATCH CONFIG
  DEFAULT_IP: "127.0.0.1",
  BATCH_SIZE: 100,
  URL_CACHE_TTL: 3600,
  BATCH_REDIS_TTL: 86400,
  REDIS_COUNTER_KEY : "global_counter",
  PREFETCH_THRESHOLD: 0.8,
  
};
