export const ERROR = {
  HEALTH_CHECK_FAILURE: "HEALTH_CHECK_FAILURE",
  INTERNAL_SERVER_ERROR:"INTERNAL_SERVER_ERROR",
  UNAUTHORIZED: "UNAUTHORIZED",
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  EMAIL_ALREADY_REGISTERED: "EMAIL_ALREADY_REGISTERED",

  CUSTOM_ALIAS_ALREADY_EXIST: "Custom alias already taken",
} as const;
